### ISSUE TITLE
Astronomy page description

### ISSUE THREAD

**Issue by ArunSahadeo** [STEMLive/stemlive.github.io#7]
@chrisorban 

I've got an astronomy page in place for the website.

Would you be willing to contribute a short description I can output on the page? :)

**Comment by chrisorban** [comment]
Do you mean you want me to define astronomy? Or just leave more of a bio on the STEMcoding page?

Thanks
Chris
________________________________

**Comment by ArunSahadeo** [comment]
The former, if that's OK.

Thanks
Arun

**Comment by chrisorban** [comment]
I would say this:

Astronomy is the study of everything that is "out there" from the edge of the earth's atmosphere to the outer reaches of the universe and everything in between.

**Comment by ArunSahadeo** [comment]
Thanks, I've used the description.

Many thanks @chrisorban :D
